apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
  namespace: argocd
spec:
  description: Infrastructure components managed by pve-infra repo
  sourceRepos:
    - "git@github.com:DJStarCOM/pve-infra.git"
    - "https://helm.openwebui.com/"
    - "docker.litellm.ai/berriai"
    - "https://langfuse.github.io/langfuse-k8s"
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
