apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  source:
    chart: open-webui
    repoURL: https://helm.openwebui.com/
    targetRevision: "12.10.0"
    helm:
      valuesObject:
        ollama:
          enabled: false
        pipelines:
          enabled: false
        tika:
          enabled: false
        openaiApiKey: ""
        openaiBaseApiUrl: "http://litellm.platform.svc.cluster.local:4000/v1"
        persistence:
          enabled: true
          size: 5Gi
        ingress:
          enabled: true
          class: traefik
          host: ai.webtechforge.dev
        resources:
          requests:
            cpu: 500m
            memory: 2Gi
          limits:
            cpu: "2"
            memory: 4Gi
        extraEnvVars:
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: litellm-masterkey
                key: masterkey
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  ignoreDifferences:
    - group: networking.k8s.io
      kind: Ingress
      jsonPointers:
        - /status
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
