apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  source:
    repoURL: git@github.com:DJStarCOM/pve-infra.git
    targetRevision: main
    path: argocd/system-apps
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
